spring:
  application:
    name: picpay_clone
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:54327/picpay_clone
    usename: postgres
    password: Postgres2019!
    initialization-mode: always
  api:
    version: 1.0.0
# Jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    format-sql: true
